Add quic patches to 3.1.0
quictls/openssl pull request #111
Opened 2023-03-14 20:22 UTC by wbl

Pretty sure I got all the version numbers and such in the rebase, but entirely possible I missed a few.

2023-03-15 13:18 UTC, nibanks commented
From my testing so far, perf looks good. I just kicked off our full MsQuic CI automation [here](https://github.com/microsoft/msquic/pull/3511) to fully test this.

2023-03-15 14:29 UTC, nibanks approved these changes
I did not look extensively through the code changes, but based on the MsQuic tests all passing, and perf looking pretty good, I'm approving this.

2023-03-16 19:53 UTC, richsalz approved these changes
why is fips-checksums.yml in this patch?  shrug.  don't care much.  approved.

2023-03-17 14:13 UTC, tmshort requested changes
Just need to add a commit to fix up the version. See https://github.com/quictls/openssl/commit/183e548d93a6aeedab0fd6cb737923a93f807b83

2023-03-17 14:13 UTC, tmshort commented on ssl/tls13_enc.c
> +#endif
A change in 3.1.0 made the `#ifdef CHARSET_EBCDIC` unnecessary. This _could_ be reduced down to the equivalent of lines 390~405 in this file.

2023-03-17 14:14 UTC, tmshort commented on README.md
> +[README-OpenSSL.md](https://github.com/quictls/openssl/blob/openssl-3.0.1%2Bquic/README-OpenSSL.md)
I see that you probably did not include the last couple README fixup commits.

2023-03-17 14:16 UTC, tmshort commented
I did do the:
```
diff <(git show -U0 $commit1) <(git show -U0 $commit2)
```
Command, and everything generally looks good. Other than the two things noted above, all I saw were context and whitespace differences.

2023-03-17 14:17 UTC, tmshort commented on ssl/tls13_enc.c
> +#endif
This is mostly a nit, since the code is still correct.

2023-03-17 14:20 UTC, tmshort commented
This is the fuzzer error:
```
clang-15: error: unsupported option '--with-fuzzer-lib=/usr/lib/libFuzzingEngine'
```
Looks to be an environment error; I wonder if it's because we don't have an up-to-date `master` branch or something?

2023-03-17 23:59 UTC, wbl commented on README.md
> +[README-OpenSSL.md](https://github.com/quictls/openssl/blob/openssl-3.0.1%2Bquic/README-OpenSSL.md)
Yeah, I think I tried to be too clever about combining them. Right thing at this point is probably to not be clever about it and cherrypick them to this.

2023-03-18 00:01 UTC, wbl commented
I'll go fix the README issue and adjust the other commit Monday and push an updated one.

2023-03-20 13:14 UTC, tmshort commented on ssl/tls13_enc.c
> +#endif
No need to make a change. But, if you were to make a change, copy the deleted code from the original file at 390~405, into the position above. Basically, you can get rid of the `#ifdef CHARSET_EBCDIC` conditional that way.

2023-03-20 16:41 UTC, wbl commented
I've added in the README commits and further bumped the version in the README. I'll pass on messing with the EBDIC stuff since Todd doesn't think there is a need and I'm not quite sure I understand it.

2023-03-27 23:10 UTC, nibanks approved these changes

2023-03-28 09:06 UTC, pheiduck commented
> I wonder if it's because we don't have an up-to-date `master` branch or something?
@tmshort Yep, This branch uses clang-15 and `master` clang-12 where the error does not occur.

2023-03-29 14:15 UTC, wbl commented
I was hoping @tmshort would be able to look again to confirm I did the README right, or @kaduk be able to take a look. If you think its good to merge despite that, go ahead: I'm not quite sure what our norms are.

2023-03-29 14:18 UTC, nibanks commented
> I was hoping @tmshort would be able to look again to confirm I did the README right, or @kaduk be able to take a look. If you think its good to merge despite that, go ahead: I'm not quite sure what our norms are.

I would like one of them to take a look as well if possible.

2023-04-13 11:44 UTC, nibanks commented
@tmshort or @kaduk would you be able to take a quick look? Thanks!

2023-04-14 14:09 UTC, tmshort commented
Sorry; I'm not getting notifications (or they are being getting lost) for this repo.

2023-04-14 14:12 UTC, tmshort approved these changes
Apologies for not looking at this in a timely manner. I have to figure out where my github notifications are going... I will try not to have this happen next time!

2023-04-14 14:13 UTC, tmshort commented
Still not worried about Fuzz. I will push the latest OpenSSL master branch, even though this repo won't use it. We will likely have to keep that one up to date as well.

2023-04-14 14:18 UTC, merged